'use strict';

let calculate = document.getElementById('start');
let plus1 = document.getElementsByTagName('button')[0];
let plus2 = document.getElementsByTagName('button')[1];
let check = document.querySelector('#deposit-check');
let input = document.querySelectorAll('.additional_income-item');
let inputs = document.getElementsByClassName('budget_day-value');
let inputs2 = document.getElementsByClassName('expenses_month-value');
let inputs3 = document.getElementsByClassName('additional_income-value');
let inputs4 = document.getElementsByClassName('additional_expenses-value');
let inputs5 = document.getElementsByClassName('income_period-value');
let inputs6 = document.getElementsByClassName('target_month-value');
let check1 = document.querySelector('.salary-amount');
let check2 = document.querySelectorAll('.income-title')[1];
let check3 = document.querySelector('.income-amount');
let check4 = document.querySelector('.additional_income-item');
let check5 = document.querySelectorAll('.additional_income-item')[1];
let check6 = document.querySelectorAll('.expenses-title')[1];
let check7 = document.querySelector('.expenses-amount');
let check8 = document.querySelector('.additional_expenses-item');
let check9 = document.querySelector('.target-amount');
let check10 = document.querySelector('.period-select');

console.log(plus1);
console.log(plus2);
console.log(calculate);
console.log(check);
console.log(input);
console.log(inputs);
console.log(inputs2);
console.log(inputs3);
console.log(inputs4);
console.log(inputs5);
console.log(inputs6);
console.log(check1);
console.log(check2);
console.log(check3);
console.log(check4);
console.log(check5);
console.log(check6);
console.log(check7);
console.log(check8);
console.log(check9);
console.log(check10);